accounts/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView
from accounts.forms import userLoginForm,UserRegisterForm
from accounts.views import Registerview ,edit_profile
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path ('login/',LoginView.as_view(authentication_form=userLoginForm), name='Login'),
    path ('register/',Registerview.as_view(), name='register'),
    path('profile/',edit_profile, name='profile')
    
    



]

projects/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.projectlistview.as_view(),name='project_list' ),
    path('project/create', views.projectCreateview.as_view(), name= 'project_create' ),
    path('project/edit/<int:pk>', views.projectUpdateview.as_view(), name= 'project_update'),
    path('project/delete/<int:pk>', views.ProjectDeleteview.as_view(), name= 'project_delete' ),
    path('task/create', views.TaskCreateview.as_view(), name= 'Task_create' ),
    path('task/edit/<int:pk>', views.TaskUpdateview.as_view(), name= 'Task_update' ),
    path('task/delete/<int:pk>', views.TaskDeleteview.as_view(), name= 'Task_delete' ),


]

projects_manage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
     path('accounts/', include('accounts.urls'))

]
  

projects/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL

# Create your models here.

#THis for category
class category (models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
#__________________________________________________________________
#this for the status of the projects
class projectstatus(models.IntegerChoices):
    PENDING = 1,'pending'
    COMPLETED = 2,'completed'
    POSTPONED = 3,'postponed'
    CANCELED =4, 'canceled'
#___________________________________________________________________


class projects (models.Model):
    title = models.CharField(max_length=255)
    status = models.IntegerField(
        choices= projectstatus.choices,
        default= projectstatus.PENDING,
    )
    description = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    #this for relationship/ one to many the many is the projects
    category = models.ForeignKey(category,on_delete=models.PROTECT)
    user = models.ForeignKey(AUTH_USER_MODEL,on_delete=models.CASCADE,null=True)
    #this for the date to be string
    def __str__(self):
        return self.title
#_______________________________________________________________________
class task(models.Model):
    description = models.TextField()
    is_complted =models.BooleanField(default=False)
    project = models.ForeignKey(projects,on_delete=models.CASCADE)
    def __str__(self):
        return self.description

    

projects/forms.py
from django import forms
from . import models

attrs = {'class':'form-control'}
class Projectcreateform(forms.ModelForm):
    class Meta:
        model  = models.projects
        fields = ['category' ,'title', 'description']
        widgets ={
            'category' : forms.Select(attrs=attrs),
            'title' : forms.TextInput(attrs=attrs),
            'description' : forms.Textarea(attrs=attrs),
        }

#__________________________________________________________________
class ProjectUpdateform(forms.ModelForm):
    class Meta:
        model  = models.projects
        fields = ['category' ,'title', 'description']
        widgets ={
            'category' : forms.Select(attrs=attrs),
            'title' : forms.TextInput(attrs=attrs),
            'status': forms.Select(attrs=attrs)
        }
        

projects/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.shortcuts import render
from . import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
# LoginRequiredMixin is to stop none register user from useing the projects management
# Create your views here.
class projectlistview( LoginRequiredMixin, ListView):
    model = models.projects
    template_name = 'project/list.html'
    paginate_by=6
    def get_queryset(self):
        query_set = super().get_queryset() 
        where = {'user_id': self.request.user}
        q = self.request.GET.get('q', None)
        if q:
            where['title__icontains'] = q
        return query_set.filter(**where)
#__________________________________________________________
class projectCreateview(LoginRequiredMixin,CreateView):
    model = models.projects
    form_class = forms.Projectcreateform
    template_name = 'project/create.html'
    success_url = reverse_lazy('project_list')
    #this def is for adding the projcet user  into the project information by sutk up the id number of the user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
#______________________________________________________________________________
class projectUpdateview(LoginRequiredMixin,UserPassesTestMixin,UpdateView ):
    model = models.projects
    form_class = forms.ProjectUpdateform
    template_name = 'project/update.html'
    # this fun is for forbdnn the none user form edit the project
    def test_func(self):
        return self.get_object().user_id == self.request.user.id
   # success_url = reverse_lazy('project_list')
   #this for stay on the same page after the update
    def get_success_url(self):
        return reverse('project_Update',args = [self.object.id])
#_____________________________________________________________________________________________________
class ProjectDeleteview(LoginRequiredMixin,UserPassesTestMixin,DeleteView ):
    model = models.projects
    template_name = 'project/delete.html '
    success_url = reverse_lazy('project_list')

    def test_func(self):
        return self.get_object().user_id == self.request.user.id
#________________________________________________________________________________
class TaskCreateview(LoginRequiredMixin,UserPassesTestMixin, CreateView):
    model = models.task
    fields= ['project', 'description']
    #this is for to give Error if someone try to ask for the t TaskCreate on the browse
    http_method_names =['post']
    def test_func(self):
        #this for get the id project 
        project_id = self.request.POST.get('project','')
        #this to coper the projet id 
        return models.project.object.get(pk = project_id).user_id== self.request.user.id
    def get_success_url(self):
        return reverse( 'project_update',args = [self.object.project.id])
#__________________________________________________________________________________
class TaskUpdateview(LoginRequiredMixin,UserPassesTestMixin, UpdateView ):
    model = models.task
    fields= ['is_completed']
    #this is for to give Error if someone try to ask for the t TaskCreate on the browse
    http_method_names =['post']
    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_Update',args = [self.object.project.id])
#_____________________________________________________________________________________
#THIS for delete the task
class TaskDeleteview(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = models.task
    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_Update',args = [self.object.project.id])

projects/templates/project/create.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="row justfy-content-md-center " >
            <div class="card col-md-6 px-0" >
                <div class="card header " >
                    <h3 class="mb-0 py-2" >{% trans 'New Project' %}</h3>
                </div>
                <div class="card-body" >
                    <form method="post">
                        {% csrf_token %}
                        {% include 'common/form.html' with form=form %}
                        <button class="btn btn-success" >
                            {% translate 'Create' %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/project/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h2> {% trans 'Alert' %} </h2>
    <form method = "post">
        {% csrf_token %}
        <p class="text-muted my-4" >
            {% trans 'Are you sure to Delete'  %} {{project.title}} ?
        </p>
        <input class="btn-btn-danger" type="submit" value="{% trans 'Delete' %}"/>
    </form>
{% endblock %}

projects/templates/project/list.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}
{% block content %}
  <div class="d-flex" >
      <h3> My Projects   </h3>
      <div>
        <a href="{% url 'project_create' %}" class="btn btn-outline-success">
            <i class = " bi bi-plus-lg"></i> {% trans 'New Project' %}
        </a>
      </div>
  </div>


  <div class="row my-5" >
      {% for project in object_list %}
      <div class="col-md-4"... >
        <div class="col-mb-3" >
          <div class="card-body" >
            <p>
              <span class="badge rounded-pill bg-dark" >
                {{project.get_status_display }}
              </span>
            </p>
            <h3 class="card-title fs-6" >{{ project.title }}</h3>
            <p class="card-text text-muted small ">{{ project.description }}</p>
            <div class="d-flex" >
              <span class="me-auto text-muted small " >
                <i class="bi bi-clock" ></i>
                <time datetime="{{ project.create_at }}">
                    {{ project.create_at|naturaltime }}
                </time>
              </span>
              <a href="{% url 'project_update' project.id %}" class="btn btn-sm btn-outline-dark mx-1 " >
                  {% trans 'Edit' %}
              </a>
              <a href="{% url 'project_delete' project.id %}" class="btn btn-sm btn-outline-danger " >
                  <i class="bi bi-trash" ></i>
              </a>
            </div> 
          </div>
        </div>
      </div>
      {% empty %}
          <div class="col-md-12" >
            <div class="h-100 p-5 bg-white border rounded-3 text-center " >
            <p> There are no projects to show </p>
            <p>
             <i class=" bi bi-emoji-frown fs-1 "></i>
            </p>
                <a href="{% url 'project_create' %}" class="btn btn-outline-success">
                <i class = " bi bi-plus-lg"></i> {% trans 'New Project' %}
                </a>
          </div>
      {% endfor %}
      {% if page_obj.paginator.count > 0 %}
      <div class="d-flex justfy-content-center bd-highlight mb-3 ">
        <nav>
          <ul class="pagination" >
              {% if page_obj.has_previous %}
              <li class="page-item" >
                <a class="page-link" href="?page={{page_obj.pervious_page_number}}">
                  {% trans 'Pervious' %}
                </a>
              </li>
              {% else %}
              <li class="page-item disabled " >
                <a class="page-link" href="#">{% trans 'Pervious' %}</a>
              </li>
              {% endif %}  {% if page_obj.paginator.count > 0 %}
              <div class="d-flex justfy-content-center bd-highlight mb-3 ">
                <nav>
                  <ul class="pagination" >
              {% if page_obj.has_next %}
                      <li class="page-item" >
                        <a class="page-link" href="?page={{page_obj.next_page_number}}">
                          {% trans 'Next' %}
                        </a>
                      </li>
              {% else %}
                      <li class="page-item disabled " >
                        <a class="page-link" href="#">{% trans 'Next' %}</a>
                      </li>
              {% endif %}
          </ul>
        </nav>
      </div>
      {% endif %}
  </div> 

{% endif %}
{% endblock %}

projects/templates/project/task.html
{% load i18n %}

<ul class="list-group" >
   {% for task in project.task_set.all%}
   <li class="list-group-item d-flex" >
        <form method = "post"  action="{% url 'Task_update' task.id %}" class="my-auto me-2" >
            {% csrf_token %}
            <input
            class="form-check-input " 
            type="checkbox" 
            name = "is_completed"   
            {% if task.is_completed %} checked {% endif %}
            onchange = " this.form.submit()  "
            />
        </form>
        <p class="my-auto me-auto" >
            {{ task.description }}
        </p>
        <form method = "post" action = "{% url 'Task_delete' task.id  %}">
            {% csrf_token %}
             <button type ="submit" class="btn" ><i class="bi bi-trash task-danger" ></i>/i></button>
            />
        </form>

   </li>
   {% endfor %} 
</ul>

<div class="card mt-2" >
    
    <form method = "post" action = "{% url 'Task_create' %}  " class="d-flex" >
        {% csrf_token %}
        <div class="input-group" >
            <input type="hidden" value="{{object.id}}" name = "project">
            <input type="text" name = "description" class="form-control" placeholder = "{% trans 'New task' %}" required />
            <input type="submit" class= "btn btn-outline-dark" value ="{% trans 'Add' %}" />
        </div>
    </form>
</div>



 

projects/templates/project/update.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <nav aria-label="breadvrumb" >
        <ol class="breadvrumb" >
            <li class = 'breadvrumb-item active' aria-current="page" >
                <h5>
                    {{ object.title }}
                </h5>
            </li>
        </ol>
    </nav>

    <div class="row" >
        <div class="col-md-3">
            <form method="post">
                <div class="card" >
                    <div class=" card-body " >
                       {% csrf_token %} 
                       {% for field in form  %}
                            <div class="mb-3" >{{field}}</div>
                       {% endfor %}
                       <div class="d-flex mt-2" >
                            <span class="me-auto text-muted small ">
                                <i class="bi bi-clock" ></i>
                                <time datetime="{{object.create_at}}">
                                    {{object.create_at|naturaltime }}
                                </time> 
                            </span>
                       </div>
                    </div> 
                    <div class="card-footer" >
                        <div class="d-grid gap-2" >
                            <button class=" btn btn-success" >
                                <i class="bi bi-save" ></i>
                                {% trans 'Save' %}
                            </button>
                            <button class=" btn btn-danger" >
                                <i class="bi bi-trash" ></i>
                                {% trans 'Delete' %}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'project/task.html' with object=object %}
        </div>
    </div>
{% endblock %} 